# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Anteater's laboratory
author:
  email: anteater1056@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    CATCH PHRASE !!
url: 'https://anteater333.github.io' # the base hostname & protocol for your site, e.g. http://example.com

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  skin: dark
  # footer에 SNS 계정 추가
  social_links:
    - { platform: twitter, user_url: "https://twitter.com/anteater333"}
    - { platform: github, user_url: "https://github.com/anteater333"}

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: minima

plugins:
    - jekyll-remote-theme
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Disqus comments service
# disqus:
#   shortname: anteater-lab
# utterances, github issues based comments service
utterances:
  name: anteater333/anteater333.github.io

# Analytics
google_analytics:  "G-XY1FSXXJM2"

# Remote theme (for latest version of theme plugin)
remote_theme: jekyll/minima