version: "3"

services:
  blog:
    image: jekyll/jekyll:3
    command: jekyll serve --open-url --force_polling --watch --drafts --livereload --trace
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ".:/srv/jekyll"
