version: '3.8'

services:
    blog:
        image: jekyll/jekyll:latest
        command: jekyll serve --open-url --force_polling --watch --drafts --livereload --trace
        ports:
            - '4000:4000'
            - '35729:35729'
        volumes:
            - '.:/srv/jekyll'
